// Base dataset (can be overridden by localStorage in app.js)
// Source: http://www.chrurck.com/?act=info.page&pcode=sub1_3

export const CATEGORIES = [
  { id: "nonlife", label: "손해보험" },
  { id: "life", label: "생명보험" },
  { id: "mutual", label: "공제회사" },
];

function clearbitLogo(domain) {
  return domain ? `https://logo.clearbit.com/${domain}` : "";
}

export const BASE_COMPANIES = [
  // 손해보험
  {
    id: "aig-nonlife",
    categoryId: "nonlife",
    name: "AIG손해보험",
    homepageUrl: "https://www.aig.co.kr/",
    systemLinkUrl: "https://sso.aig.co.kr/gaLogin/gaLogin.jsp",
    logoUrl: clearbitLogo("aig.co.kr"),
    callCenter: "1544-2792",
    inCallMonitoring: "1544-2792",
    helpdesk: "02-2260-6855",
    claimFax: "02-2011-4607",
    termsUrl: "https://www.aig.co.kr/wo/dpwot001.html?menuId=MS702",
    claimFormUrl:
      "https://www.aig.co.kr/wm/content.html?contentId=DPWMS406&menuId=MS406",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "db-nonlife",
    categoryId: "nonlife",
    name: "DB손해보험",
    homepageUrl: "https://www.idbins.com/",
    systemLinkUrl: "https://www.mdbins.com",
    logoUrl: clearbitLogo("idbins.com"),
    callCenter: "1588-0100",
    inCallMonitoring: "1566-0757",
    helpdesk: "02-2262-1241",
    claimFax: "0505-181-4862",
    termsUrl: "https://www.idbins.com/FWMAIV1534.do",
    claimFormUrl:
      "https://www.idbins.com/pc/bizxpress/ct/dc/FWCUSV1301.shtm",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "kb-nonlife",
    categoryId: "nonlife",
    name: "KB손해보험",
    homepageUrl: "https://www.kbinsure.co.kr/",
    systemLinkUrl: "http://sales.kbinsure.co.kr",
    logoUrl: clearbitLogo("kbinsure.co.kr"),
    callCenter: "1544-0114",
    inCallMonitoring: "1544-0019",
    helpdesk: "1544-8119",
    claimFax: "0505-136-6500",
    termsUrl: "https://www.kbinsure.co.kr/CG802030001.ec",
    claimFormUrl: "https://www.kbinsure.co.kr/CG205020001.ec",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "mg-nonlife",
    categoryId: "nonlife",
    name: "MG손해보험",
    homepageUrl: "https://www.mggeneralins.com/",
    systemLinkUrl: "https://mganet.mggeneralins.com",
    logoUrl: clearbitLogo("mggeneralins.com"),
    callCenter: "1588-5959",
    inCallMonitoring: "1577-3777",
    helpdesk: "02-3788-2261",
    claimFax: "0505-088-1646",
    termsUrl: "https://www.yebyeol.co.kr/PB031210DM.scp?menuId=MN0803006",
    claimFormUrl: "https://www.yebyeol.co.kr/LG011010DM.scp",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "nh-nonlife",
    categoryId: "nonlife",
    name: "NH농협손해보험",
    homepageUrl: "https://www.nhfire.co.kr/",
    systemLinkUrl: "http://www.nhfire.co.kr/fc/fd.nhfire",
    logoUrl: clearbitLogo("nhfire.co.kr"),
    callCenter: "1644-9000",
    inCallMonitoring: "1644-9600",
    helpdesk: "1644-0090",
    claimFax: "0505-060-7000",
    termsUrl:
      "https://www.nhfire.co.kr/announce/productAnnounce/retrieveInsuranceProductsAnnounce.nhfire",
    claimFormUrl:
      "https://www.nhfire.co.kr/customer/bilgdcm/retrieveBilgDcmList.nhfire",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "lotte-nonlife",
    categoryId: "nonlife",
    name: "롯데손해보험",
    homepageUrl: "https://www.lotteins.co.kr/",
    systemLinkUrl: "http://lottero.lotteins.co.kr",
    logoUrl: clearbitLogo("lotteins.co.kr"),
    callCenter: "1588-3344",
    inCallMonitoring: "1600-5182",
    helpdesk: "1599-8260",
    claimFax: "0507-333-9999",
    termsUrl: "https://lotteins.co.kr/web/C/D/H/cdh190.jsp",
    claimFormUrl: "https://lotteins.co.kr/web/C/D/C/cdc_claim_0502.jsp",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "meritz-nonlife",
    categoryId: "nonlife",
    name: "메리츠화재",
    homepageUrl: "https://www.meritzfire.com/",
    systemLinkUrl: "http://sales.meritzfire.com",
    logoUrl: clearbitLogo("meritzfire.com"),
    callCenter: "1566-7711",
    inCallMonitoring: "1577-7711",
    helpdesk: "02-3786-2777",
    claimFax: "0505-021-3400",
    termsUrl:
      "https://www.meritzfire.com/disclosure/product-announcement/product-list.do#!/",
    claimFormUrl:
      "https://www.meritzfire.com/compensation/longterm-insurance/request-document.do#!/",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "samsung-fire",
    categoryId: "nonlife",
    name: "삼성화재",
    homepageUrl: "https://www.samsungfire.com/",
    systemLinkUrl: "https://erp.samsungfire.com",
    logoUrl: clearbitLogo("samsungfire.com"),
    callCenter: "1588-5114",
    inCallMonitoring: "1566-0553",
    helpdesk: "1899-5005",
    claimFax: "0505-162-0872",
    termsUrl: "https://www.samsungfire.com/page/VH.REIF0011.do",
    claimFormUrl: "https://www.samsungfire.com/claim/P_P03_01_02_009.html",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "hana-nonlife",
    categoryId: "nonlife",
    name: "하나손해보험",
    homepageUrl: "https://www.hanainsure.co.kr/",
    systemLinkUrl: "https://sfa.saleshana.com",
    logoUrl: clearbitLogo("hanainsure.co.kr"),
    callCenter: "1566-3000",
    inCallMonitoring: "1566-3000 연결 후 2번",
    helpdesk: "02-6670-8110",
    claimFax: "0504-3764-0765",
    termsUrl: "https://www.hanainsure.co.kr/w/disclosure/product/saleProduct",
    claimFormUrl:
      "https://www.hanainsure.co.kr/w/claim/carReward/rewardDocumentGuide",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "hanwha-nonlife",
    categoryId: "nonlife",
    name: "한화손해보험",
    homepageUrl: "https://www.hwgeneralins.com/",
    systemLinkUrl: "http://portal.hwgeneralins.com",
    logoUrl: clearbitLogo("hwgeneralins.com"),
    callCenter: "1566-8000",
    inCallMonitoring: "1670-1882",
    helpdesk: "02-316-0111",
    claimFax: "0502-779-1004",
    termsUrl: "https://www.hwgeneralins.com/notice/ir/product-ing01.do",
    claimFormUrl: "https://www.hwgeneralins.com/fplaza/compensation/receipt01.do",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "hyundai-nonlife",
    categoryId: "nonlife",
    name: "현대해상",
    homepageUrl: "https://www.hi.co.kr/",
    systemLinkUrl: "https://sp.hi.co.kr",
    logoUrl: clearbitLogo("hi.co.kr"),
    callCenter: "1588-5656",
    inCallMonitoring: "1577-3223",
    helpdesk: "02-2628-4567",
    claimFax: "0507-774-6060",
    termsUrl:
      "https://www.hi.co.kr/serviceAction.do?view=bin/PA/03/HHPA03010M#none",
    claimFormUrl: "https://www.hi.co.kr/serviceAction.do?menuId=100631",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "heungkuk-fire",
    categoryId: "nonlife",
    name: "흥국화재",
    homepageUrl: "https://www.heungkukfire.co.kr/",
    systemLinkUrl: "http://upride.heungkukfire.co.kr",
    logoUrl: clearbitLogo("heungkukfire.co.kr"),
    callCenter: "1688-1688",
    inCallMonitoring: "1688-6997",
    helpdesk: "031-786-8088",
    claimFax: "0504-800-0700",
    termsUrl:
      "https://www.heungkukfire.co.kr/FRW/announce/insGoodsGongsiSale.do",
    claimFormUrl:
      "https://www.heungkukfire.co.kr/FRW/compensation/accidentDocInfo.do",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "chubb-nonlife",
    categoryId: "nonlife",
    name: "처브 에이스 손해보험",
    homepageUrl: "https://www.chubb.com/kr-kr/",
    systemLinkUrl: "https://www.chubb.com/kr-kr/",
    logoUrl: clearbitLogo("chubb.com"),
    callCenter: "1566-5800",
    inCallMonitoring: "02-2127-2308 (치아: 02-6913-8482)",
    helpdesk: "",
    claimFax: "",
    termsUrl: "https://www.chubb.com/kr-kr/disclosure/product.html",
    claimFormUrl: "https://www.chubb.com/kr-kr/claims/report-a-claim.html",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "axa-nonlife",
    categoryId: "nonlife",
    name: "AXA 손해보험",
    homepageUrl: "https://www.axa.co.kr/",
    systemLinkUrl:
      "https://www.axa.co.kr/ActionControler.action?screenID=SHCM0000&actionID=I01",
    logoUrl: clearbitLogo("axa.co.kr"),
    callCenter: "1566-1566",
    inCallMonitoring: "콜센터 가상번호 부여",
    helpdesk: "",
    claimFax: "",
    termsUrl:
      "https://www.axa.co.kr/AsianPlatformInternet/html/axacms/common/intro/disclosure/insurance/index.html",
    claimFormUrl:
      "https://www.axa.co.kr/AsianPlatformInternet/html/axacms/shcl/pa/process/index.html",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },

  // 생명보험
  {
    id: "aia-life",
    categoryId: "life",
    name: "AIA생명",
    homepageUrl: "https://www.aia.co.kr/",
    systemLinkUrl: "https://imap.aia.co.kr",
    logoUrl: clearbitLogo("aia.co.kr"),
    callCenter: "1588-9898",
    inCallMonitoring: "1588-2513",
    helpdesk: "1588-2937",
    claimFax: "02-2021-4540",
    termsUrl: "https://www.aia.co.kr/ko/our-products.html",
    claimFormUrl: "https://www.aia.co.kr/ko/help-support/forms.html",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "abl-life",
    categoryId: "life",
    name: "ABL생명",
    homepageUrl: "https://www.abllife.co.kr/",
    systemLinkUrl: "http://ga.abllife.co.kr",
    logoUrl: clearbitLogo("abllife.co.kr"),
    callCenter: "1588-6500",
    inCallMonitoring: "1566-1002",
    helpdesk: "02-3787-8583",
    claimFax: "콜센터 가상번호 부여",
    termsUrl:
      "https://www.abllife.co.kr/st/pban/prdtPban/whlPrdt/whlPrdt1/whlPrdt11?page=index",
    claimFormUrl:
      "https://www.abllife.co.kr/st/custDesk/insSrvcGudn/acdtInsmClamGudn/acdtInsmClamGudn3?page=index",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "cardif-life",
    categoryId: "life",
    name: "BNP파리바카디프",
    homepageUrl: "https://www.cardif.co.kr/",
    systemLinkUrl: "http://ga.cardif.co.kr",
    logoUrl: clearbitLogo("cardif.co.kr"),
    callCenter: "1688-1118",
    inCallMonitoring: "1688-1118",
    helpdesk: "1577-3435",
    claimFax: "콜센터 가상번호 부여",
    termsUrl: "https://www.cardif.co.kr/disclosure/papag101.do",
    claimFormUrl: "https://www.cardif.co.kr/customer-center/hcwgi001.do",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "db-life",
    categoryId: "life",
    name: "DB생명",
    homepageUrl: "https://www.idblife.com/",
    systemLinkUrl: "http://etopia.dongbulife.com",
    logoUrl: clearbitLogo("idblife.com"),
    callCenter: "1588-3131",
    inCallMonitoring: "02-6470-7663",
    helpdesk: "02-2119-5151",
    claimFax: "0505-129-3134",
    termsUrl: "https://www.idblife.com/notice/product/sale",
    claimFormUrl: "https://www.idblife.com/support/guide/acbf_clm",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "dgb-life",
    categoryId: "life",
    name: "DGB생명",
    homepageUrl: "https://www.dgbfnlife.com/",
    systemLinkUrl: "https://fgs.dgbfnlife.com:8443",
    logoUrl: clearbitLogo("dgbfnlife.com"),
    callCenter: "1588-4770",
    inCallMonitoring: "1588-4770",
    helpdesk: "02-2087-9594",
    claimFax: "콜센터 접수 후 0505-083-5420",
    termsUrl: "https://www.dgbfnlife.com/BA/BA_A020.do",
    claimFormUrl: "https://www.dgbfnlife.com/BB/BB_D010.do",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "ibk-pension",
    categoryId: "life",
    name: "IBK연금보험",
    homepageUrl: "https://www.ibki.co.kr/",
    systemLinkUrl: "https://vpn.ibkinsu.co.kr",
    logoUrl: clearbitLogo("ibki.co.kr"),
    callCenter: "1577-4117",
    inCallMonitoring: "02-2270-1661",
    helpdesk: "02-2270-1577",
    claimFax: "",
    termsUrl: "https://www.ibki.co.kr/process/HP_PBANO_PDT_SP_INDV",
    claimFormUrl:
      "https://www.ibki.co.kr/process/HP_CSCETR_POSN_DOC_INS_LIST?bltb_cod=SC000014&sctn=in&TAB=in",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "kb-life",
    categoryId: "life",
    name: "KB라이프생명",
    homepageUrl: "https://www.kblife.co.kr/",
    systemLinkUrl: "http://esfa.kbli.co.kr",
    logoUrl: clearbitLogo("kblife.co.kr"),
    callCenter: "1588-3374",
    inCallMonitoring: "1566-2730",
    helpdesk: "(구)푸르덴셜생명: 라이프파트너 / (구)KB생명: 02-6220-9912",
    claimFax: "",
    termsUrl: "https://www.kblife.co.kr/?/=true&tab=currently-selling",
    claimFormUrl:
      "https://www.kblife.co.kr/customer-center/informRequiredDocument.do",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "kdb-life",
    categoryId: "life",
    name: "KDB생명",
    homepageUrl: "https://www.kdblife.co.kr/",
    systemLinkUrl: "http://kss.kdblife.co.kr",
    logoUrl: clearbitLogo("kdblife.co.kr"),
    callCenter: "1588-4040",
    inCallMonitoring: "1588-4040",
    helpdesk: "02-6303-2771",
    claimFax: "콜센터 접수 후 02-2669-6500",
    termsUrl: "https://www.kdblife.co.kr/ajax.do?scrId=HDLMA002M02P",
    claimFormUrl: "https://www.kdblife.co.kr/ajax.do?scrId=HCSCT006M01P",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "nh-life",
    categoryId: "life",
    name: "NH농협생명",
    homepageUrl: "https://www.nhlife.co.kr/",
    systemLinkUrl: "http://www.nhlife.co.kr/nhsmart.nhl",
    logoUrl: clearbitLogo("nhlife.co.kr"),
    callCenter: "1544-4000",
    inCallMonitoring: "1544-4422",
    helpdesk: "02-3786-8800",
    claimFax: "02-6971-6040",
    termsUrl: "https://www.nhlife.co.kr/ho/on/HOON0004M00.nhl",
    claimFormUrl: "https://www.nhlife.co.kr/ho/cc/HOCC0010M00.nhl",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "kyobo-life",
    categoryId: "life",
    name: "교보생명",
    homepageUrl: "https://www.kyobo.com/",
    systemLinkUrl: "https://ga.kyobo.com",
    logoUrl: clearbitLogo("kyobo.com"),
    callCenter: "1588-1001",
    inCallMonitoring: "1588-1636",
    helpdesk: "02-721-3130",
    claimFax: "콜센터 가상번호 부여",
    termsUrl:
      "https://www.kyobo.com/dgt/web/product-official/all-product/search",
    claimFormUrl:
      "https://www.kyobo.com/dgt/web/customer/support/need-papers/list",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "tongyang-life",
    categoryId: "life",
    name: "동양생명",
    homepageUrl: "https://www.myangel.co.kr/",
    systemLinkUrl: "http://1004.myangel.co.kr",
    logoUrl: clearbitLogo("myangel.co.kr"),
    callCenter: "1577-1004",
    inCallMonitoring: "080-899-1004",
    helpdesk: "02-728-9900",
    claimFax: "02-3289-4517",
    termsUrl: "https://www.myangel.co.kr/paging/WE_AC_WEPAAP020100L",
    claimFormUrl: "https://www.myangel.co.kr/process/main",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "lina-life",
    categoryId: "life",
    name: "라이나생명",
    homepageUrl: "https://www.lina.co.kr/",
    systemLinkUrl: "https://ga.lina.co.kr",
    logoUrl: clearbitLogo("lina.co.kr"),
    callCenter: "1588-0058",
    inCallMonitoring: "1588-2442",
    helpdesk: "1588-2215",
    claimFax: "02-6944-1200",
    termsUrl:
      "https://www.lina.co.kr/disclosure/product_list.htm?productState=01&productKind=01",
    claimFormUrl:
      "https://www.lina.co.kr/cyber/accident-insurance/document-zero",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "metlife-life",
    categoryId: "life",
    name: "메트라이프",
    homepageUrl: "https://www.metlife.co.kr/",
    systemLinkUrl: "http://metplus.metlife.co.kr",
    logoUrl: clearbitLogo("metlife.co.kr"),
    callCenter: "1588-9600",
    inCallMonitoring: "1588-9609",
    helpdesk: "1899-0751",
    claimFax: "02-3469-9428",
    termsUrl: "https://brand.metlife.co.kr/pn/paReal/insuProductDisclMain.do",
    claimFormUrl: "https://cyber.metlife.co.kr/claim/requiredDocumentNotice",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "miraeasset-life",
    categoryId: "life",
    name: "미래에셋",
    homepageUrl: "https://life.miraeasset.com/",
    systemLinkUrl: "http://www.loveageplan.com",
    logoUrl: clearbitLogo("life.miraeasset.com"),
    callCenter: "1588-0220",
    inCallMonitoring: "1588-0220",
    helpdesk: "02-3271-5108",
    claimFax: "콜센터 가상번호 부여",
    termsUrl:
      "https://life.miraeasset.com/micro/disclosure/product/PC-HO-080301-000000.do",
    claimFormUrl:
      "https://life.miraeasset.com/home/index.do#MO-HO-030501-010000",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "samsung-life",
    categoryId: "life",
    name: "삼성생명",
    homepageUrl: "https://www.samsunglife.com/",
    systemLinkUrl: "http://u-channel-ga.samsunglife.com",
    logoUrl: clearbitLogo("samsunglife.com"),
    callCenter: "1588-3114",
    inCallMonitoring: "1588-3115",
    helpdesk: "02-311-4500",
    claimFax: "콜센터 가상번호 부여",
    termsUrl:
      "https://www.samsunglife.com/individual/products/disclosure/sales/PDO-PRPRI010110M",
    claimFormUrl:
      "https://www.samsunglife.com/individual/mysamsunglife/insurance/internet/MDP-MYINT020110M",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "shinhan-life",
    categoryId: "life",
    name: "신한라이프",
    homepageUrl: "https://www.shinhanlife.co.kr/",
    systemLinkUrl: "https://ga.shinhanlife.co.kr",
    logoUrl: clearbitLogo("shinhanlife.co.kr"),
    callCenter: "1588-5580",
    inCallMonitoring: "1522-2285",
    helpdesk: "02-3455-4119",
    claimFax: "콜센터 가상번호 부여",
    termsUrl: "https://www.shinhanlife.co.kr/hp/cdhi0010.do",
    claimFormUrl: "https://www.shinhanlife.co.kr/hp/cdhf0020t02.do",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "chubb-life",
    categoryId: "life",
    name: "처브라이프",
    homepageUrl: "https://www.chubblife.co.kr/",
    systemLinkUrl: "http://esmart.chubblife.co.kr",
    logoUrl: clearbitLogo("chubblife.co.kr"),
    callCenter: "1599-4600",
    inCallMonitoring: "1599-4600",
    helpdesk: "1599-4646",
    claimFax: "02-3480-7801",
    termsUrl: "https://www.chubblife.co.kr/front/official/sale/list.do",
    claimFormUrl:
      "https://www.chubblife.co.kr/front/ctmcenter/insurance/listDocu.do",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "fubonhyundai-life",
    categoryId: "life",
    name: "푸본현대생명",
    homepageUrl: "https://www.fubonhyundai.com/",
    systemLinkUrl: "http://wsfa.fubonhyundai.com",
    logoUrl: clearbitLogo("fubonhyundai.com"),
    callCenter: "1577-3311",
    inCallMonitoring: "080-860-1212",
    helpdesk: "0505-106-0311",
    claimFax: "",
    termsUrl: "https://www.fubonhyundai.com/#CUSI150102010101",
    claimFormUrl: "https://www.fubonhyundai.com/#CUSI070100000000",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "heungkuk-life",
    categoryId: "life",
    name: "흥국생명",
    homepageUrl: "https://www.heungkuklife.co.kr/",
    systemLinkUrl: "https://e-life.heungkuklife.co.kr",
    logoUrl: clearbitLogo("heungkuklife.co.kr"),
    callCenter: "1588-2288",
    inCallMonitoring: "1877-7006",
    helpdesk: "031-786-8088",
    claimFax: "콜센터 가상번호 부여",
    termsUrl:
      "https://www.heungkuklife.co.kr/front/public/saleProduct.do?searchFlgSale=Y",
    claimFormUrl:
      "https://www.heungkuklife.co.kr/jsps/front/help/customer_require_tab.jsp",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "hanwha-life",
    categoryId: "life",
    name: "한화생명",
    homepageUrl: "https://www.hanwhalife.com/",
    systemLinkUrl: "https://hmp.hanwhalife.com/online/ga",
    logoUrl: clearbitLogo("hanwhalife.com"),
    callCenter: "1588-6363",
    inCallMonitoring: "1800-6633",
    helpdesk: "02-1522-6379",
    claimFax: "콜센터 가상번호 부여",
    termsUrl:
      "https://www.hanwhalife.com/main/disclosure/goods/disclosurenotice/DF_GDDN000_P10000.do?MENU_ID1=DF_GDGL000",
    claimFormUrl:
      "https://www.hanwhalife.com/static/main/myPage/insurance/accident/document/MY_INAPADC_T10000.jsp",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "hana-life",
    categoryId: "life",
    name: "하나생명",
    homepageUrl: "https://www.hanalife.co.kr/",
    systemLinkUrl: "https://www.hanalife.co.kr/",
    logoUrl: clearbitLogo("hanalife.co.kr"),
    callCenter: "1577-1112",
    inCallMonitoring: "1577-1112",
    helpdesk: "02-6719-6722",
    claimFax: "",
    termsUrl: "https://www.hanalife.co.kr/anm/product/allProduct.do?status=on",
    claimFormUrl:
      "https://www.hanalife.co.kr/csc/accidentGuideRenew/accidentPaymentDocument.do",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },

  // 공제회사
  {
    id: "kfcc-mutual",
    categoryId: "mutual",
    name: "MG새마을금고보험",
    homepageUrl: "https://www.kfcc.co.kr/",
    systemLinkUrl: "https://insu.kfcc.co.kr/main.do",
    logoUrl: clearbitLogo("kfcc.co.kr"),
    callCenter: "1599-9010",
    inCallMonitoring: "콜센터 가상번호 부여",
    helpdesk: "https://insu.kfcc.co.kr/ino/inoGuide.do",
    claimFax: "https://insu.kfcc.co.kr/ics/cybIcsChargeProcessinfo.do",
    termsUrl: "",
    claimFormUrl: "",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "ktcu-mutual",
    categoryId: "mutual",
    name: "더케이 교직원공제",
    homepageUrl: "https://www.ktcu.or.kr/",
    systemLinkUrl: "https://www.ktcu.or.kr/MH/MH-P010M01.do",
    logoUrl: clearbitLogo("ktcu.or.kr"),
    callCenter: "1577-3993",
    inCallMonitoring: "02-3278-9696",
    helpdesk: "https://www.ktcu.or.kr/IS/IS-P170M01.do",
    claimFax: "https://www.ktcu.or.kr/IS/IS-P120T01.do",
    termsUrl: "",
    claimFormUrl: "",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "epost-mutual",
    categoryId: "mutual",
    name: "우체국 보험",
    homepageUrl: "https://epostlife.go.kr/",
    systemLinkUrl: "https://epostlife.go.kr/LNLNDM10DM.do",
    logoUrl: clearbitLogo("epostlife.go.kr"),
    callCenter: "1599-0100",
    inCallMonitoring: "지역별로 상이(콜센터 문의)",
    helpdesk: "https://mall.epostbank.go.kr/IPPSKE0000.do",
    claimFax: "https://epostlife.go.kr/IPDSDC0001.do",
    termsUrl: "",
    claimFormUrl: "",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "suhyup-mutual",
    categoryId: "mutual",
    name: "수협공제",
    homepageUrl: "https://www.suhyup-bank.com/",
    systemLinkUrl: "https://www.suhyup-bank.com/",
    logoUrl: clearbitLogo("suhyup-bank.com"),
    callCenter: "1588-4119",
    inCallMonitoring: "콜센터 가상번호 부여",
    helpdesk: "https://www.suhyup-bank.com/ib20/mnu/FPD00127#859",
    claimFax: "https://www.suhyup-bank.com/",
    termsUrl: "",
    claimFormUrl: "",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
  {
    id: "cu-mutual",
    categoryId: "mutual",
    name: "신협공제",
    homepageUrl: "https://www.cu.co.kr/",
    systemLinkUrl: "https://openbank.cu.co.kr/?sub=6000",
    logoUrl: clearbitLogo("cu.co.kr"),
    callCenter: "1544-3030",
    inCallMonitoring: "콜센터 가상번호 부여",
    helpdesk: "https://openbank.cu.co.kr/?sub=6000",
    claimFax: "https://openbank.cu.co.kr/?sub=6000",
    termsUrl: "",
    claimFormUrl: "",
    roles: {
      branchManager: { name: "", phone: "" },
      manager: { name: "", phone: "" },
      admin: { name: "", phone: "" },
    },
  },
];

